arb-dir: lib/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
translate: true                             # Enable translation 
generate : true                             # auto run flutter gen-l10n
key-prefix: context.localization.   # Key prefix for translation
auto-name-key: true                         # Generate key name based on text
synthetic-package: false